### Simple hello world
GET http://localhost:5000/hello

### Hello with param
GET http://localhost:5000/hello?name=Flask-APP

### Call Flow
POST http://localhost:5000/call-flow
content-type: application/json

{
    "userMessage": "How can I close a flask app in terminal?"
}
